baseURL: /
title: Pachyderm's Docs

enableGitInfo: true 
enableEmoji: true 
enableRobotsTXT: true 
theme: pach-emdash

staticDir: "/themes/pach-emdash/static"

outputs: 
  home: [ "HTML", "JSON"]
  page: [ "HTML", "JSON"]
  section: [ "HTML", "JSON"]
  list: [ "HTML", "JSON"]
  taxonomies: [ "HTML", "JSON"]

params:
  # Feature Switches #

  ## Branding features
  logos:
    nav:  "/../images/pachLogo.svg"
    footer: "/../images/footerLogo.svg"

  ## Content features
  childPages: 
    display: true # displays child pages of a section.
    grandchildren: true # displays first 7 grandchildren as buttons in the card.
  editLink: 
    display: true #  displays a link to the corresponding github file for a given page; githubUrl must be set.
    githubUrl: https://github.com/pachyderm/docs/tree/main/content/  # should end with content/ 
  giscus: true # displays giscus commenting on single pages.
  heroBanner:
    single: true # displays hero section with a background image, title, description, and date on single pages.
    section: true # displays hero section [...] on section pages.
    list: true # displays hero section [...] on list pages. 
    glossary: true # displays hero section [...] on glossary pages (layout:glossary frontmatter). 
  relatedArticles: true # displays related content on page.
  seriesButton: true #  displays a "Read the <> series" button at the bottom of a page with series frontmatter.
  toc: true #  displays a table of contents in a page; can be overridden by individual page settings. (WIP)

  ## HomePage Features
   # TODO: add date sort to range on featureDisplayVideos
  Videos: false # displays first 3 videos from "/tutorials/videos/", sorted by date.
  CommunityDetails: true  # displays slack and other community details (WIP)
  
  ## Release Features
  versionDropdown: true # displays a top-nav dropdown with top-level sections served as versioned documentation. 
  downloads: true # Enables displaying the download dropdown (requires release.patch)
  releaseInfo:
    latest: "2.3.x" # displays matching directory's sections on home page; if blank, all directories are displayed.
    patch: "2.3.2" # Used to generate download links


  ## Nav features 
  navLevel: true  #  displays level-2 directory items in the file tree.
  breadcrumbs: true # displays a trail of breadcrumbs
  nextPrev: true #  displays the next and previous article available on single page.

  ## Testing Features
  defaultCss: false # displays default bulma css only without branding.

## Feature Ideas 
## 1. Create a layouts/partials/brand.css file that has hugo variables to control some css from the config.yaml file. 

sitemap:
  changeFreq: monthly 
  fileName: sitemap.xml 
  priority: 0.8 

taxonomies:
  tag: tags 
  category: categories 
  series: series 

markup:
  goldmark:
    renderer:
      unsafe: true

